version: '3.7'

services:
  app:
    image: node:16.16.0-alpine3.15
    command: sh -c "apk add opus-tools && yarn install && yarn start"
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:14.3-alpine
    ports:
      - 5432:5432
    volumes:
      - bhaka-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: bhaka
      POSTGRES_DB: bhaka
      POSTGRES_PASSWORD: bhakasuper
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  bhaka-db-data:
